"""Search arXiv for spatial omics prediction papers and generate formatted output."""

import urllib.request
import urllib.parse
import xml.etree.ElementTree as ET
import datetime
import os

QUERIES = [
    # Spatial omics broad
    'all:"spatial omics" AND all:"prediction"',
    'all:"spatial omics" AND all:"deep learning"',
    # Spatial transcriptomics
    'all:"spatial transcriptomics" AND all:"inference"',
    'all:"spatial transcriptomics" AND all:"prediction"',
    'all:"spatial transcriptomics" AND all:"deep learning"',
    'all:"spatial transcriptomics" AND all:"gene expression"',
    'all:"spatial gene expression" AND all:"histology"',
    # Gene / cell type prediction from images
    'all:"gene expression prediction" AND all:"histology"',
    'all:"cell type" AND all:"spatial transcriptomics" AND all:"prediction"',
    'all:"cell type deconvolution" AND all:"spatial"',
    # Spatial proteomics
    'all:"spatial proteomics" AND all:"prediction"',
    'all:"spatial proteomics" AND all:"deep learning"',
    # H&E image to omics
    'all:"histology" AND all:"transcriptomics" AND all:"prediction"',
    'all:"H&E" AND all:"gene expression" AND all:"predict"',
    'all:"pathology" AND all:"spatial transcriptomics" AND all:"neural network"',
]
MAX_RESULTS = 50
ARXIV_API = "http://export.arxiv.org/api/query"
NS = {"atom": "http://www.w3.org/2005/Atom"}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")
OUTPUT_TXT = os.path.join(OUTPUT_DIR, "arxiv_results.txt")
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT_MD = os.path.join(PROJECT_ROOT, "ARXIV.md")


def fetch_arxiv(query: str, max_results: int = MAX_RESULTS) -> str:
    params = urllib.parse.urlencode({
        "search_query": query,
        "start": 0,
        "max_results": max_results,
        "sortBy": "submittedDate",
        "sortOrder": "descending",
    })
    url = f"{ARXIV_API}?{params}"
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8")


def parse_entries(xml_text: str) -> list[dict]:
    root = ET.fromstring(xml_text)
    entries = []
    for entry in root.findall("atom:entry", NS):
        arxiv_id = entry.find("atom:id", NS).text.strip()
        # Skip feed-level result entries without real IDs
        if "/abs/" not in arxiv_id:
            continue
        title = " ".join(entry.find("atom:title", NS).text.split())
        abstract = " ".join(entry.find("atom:summary", NS).text.split())
        published = entry.find("atom:published", NS).text[:10]  # YYYY-MM-DD
        link = arxiv_id.replace("http://", "https://")
        entries.append({
            "id": arxiv_id.split("/abs/")[-1],
            "title": title,
            "link": link,
            "date": published,
            "abstract": abstract,
        })
    return entries


def deduplicate(all_entries: list[dict]) -> list[dict]:
    seen: set[str] = set()
    unique = []
    for e in all_entries:
        if e["id"] not in seen:
            seen.add(e["id"])
            unique.append(e)
    return unique


def write_txt(papers: list[dict], path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for p in papers:
            f.write(f"Title: {p['title']}\n")
            f.write(f"Link: {p['link']}\n")
            f.write(f"Date: {p['date']}\n")
            f.write(f"Abstract: {p['abstract']}\n")
            f.write("---\n")


def write_md(papers: list[dict], path: str) -> None:
    today = datetime.date.today().isoformat()
    lines = [
        "# arXiv Spatial Omics Prediction Papers",
        "",
        f"Last update: {today}.",
        "",
        "Auto-generated by `python tools/arxiv_search.py`.",
        "",
        "| Published | Title | Assignment | Modalities | Platform | Code |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for p in papers:
        title_cell = f"[{p['title']}]({p['link']})"
        lines.append(f"| {p['date']} arXiv | {title_cell} | - | - | - | - |")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> None:
    all_entries: list[dict] = []
    for q in QUERIES:
        print(f"Querying: {q}")
        xml = fetch_arxiv(q)
        entries = parse_entries(xml)
        print(f"  Found {len(entries)} results")
        all_entries.extend(entries)

    papers = deduplicate(all_entries)
    papers.sort(key=lambda p: p["date"], reverse=True)
    print(f"Total unique papers: {len(papers)}")

    write_txt(papers, OUTPUT_TXT)
    print(f"Wrote {OUTPUT_TXT}")

    write_md(papers, OUTPUT_MD)
    print(f"Wrote {OUTPUT_MD}")


if __name__ == "__main__":
    main()
